version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - testprojects
    volumes:
      - mongodb:/data/db

networks:
  testprojects:

volumes:
  mongodb:
